### ISSUE TITLE
Dart 2 iterable methods throw UnimplementedError

### ISSUE THREAD

**Issue by har79** [google/built_collection.dart#135]
We tried to make use of `followedBy` on a BuiltList and were surprised when it threw `UnimplementedError` particularly since this isn't a method that would mutate the state. Why does this throw an error? Would it be possible to make BuiltList extend IterableMixin to gain access to this and other methods?

**Comment by davidmorgan** [comment]
Yes, this is because they are not implemented yet. Sorry about that.

The right fix is likely to delegate the new non-mutating methods to the equivalent methods on `List`. This is potentially more efficient than using `IterableMixin`.

I intend to do this as soon as I can get to it; hopefully in the next week or two.

**Comment by davidmorgan** [comment]
Sent a PR implementing `followedBy`.

The other methods don't work in Dart 1, so I will hold off on implementing those--they are dangerous for code that might run in Dart 1 and Dart 2.

**Comment by har79** [comment]
Thanks!
