### ISSUE TITLE
Allow null items?

### ISSUE THREAD

**Issue by kentcb** [google/built_collection.dart#140]
Maybe I'm missing something obvious here, but I don't understand why `null` items within a built collection are not permitted, or at least optionally enabled via `@nullable`.

It means I cannot perform a relatively straightforward conversion from some existing `List<T>` code that allows nulls to `BuiltList<T>`. I instead have to devise some kind of wrapper type (`Option<T>`) or sentinel value, and doing so isn't exactly going to result in intuitive results.

**Comment by davidmorgan** [comment]
Thanks.

I do see that it could be useful sometimes; but I think it's rare enough that it doesn't carry its weight as a feature. We'd have to add either another implementation class, which potentially stops compilers optimizing/inlining, or a boolean in every instance. And, if/when Dart gets non-nullable-by-default, it will lead to a less nice API because we will have to mark everything nullable, even if we usually know at runtime that they can't be null.

Note that the Guava collections, which built_collection is loosely based on, made the same decision, and was happy with the result:

https://github.com/google/guava/issues/1782#issuecomment-297605894

So, I think this is unlikely to change. Sorry.

**Comment by kentcb** [comment]
Understood, and thanks for the response. FWIW, I ended up using quiver's `Optional<T>` type, so I have `BuiltList<Optional<MyType>>`. In a way, it's better than using `null`, which isn't really surprising, but required a bit more work to get it working.

**Comment by davidmorgan** [comment]
Thanks. I agree, `Optional` is the way to go if you need this.
