### ISSUE TITLE
Question - nested BuiltMap

### ISSUE THREAD

**Issue by kostaa** [google/built_collection.dart#144]
Is it possible to nest BuiltMaps like this

```javascript
BuiltMap<Type, BuiltMap<String, Entity>> get entities;
```
If yes what is the correct way of updating the nested `BuiltMap<String, Entity>` map?

I am trying to use this structure within a Redux store (based on the built_redux implementation) with a reducer updating the map like this (T2 is a tuple):

```javascript
/// Updates an existing entity or inserts a new one.
void upsert(AppState s, Action<T2<Type, Entity>> a, AppStateBuilder b) {
  b.entities.putIfAbsent(a.payload.p1, () => new BuiltMap<String, Entity>());
  b.entities[a.payload.p1].toBuilder()[a.payload.p2.id] = a.payload.p2;
}
```
When running this test

```javascript
store.actions.upsert(new T2<Type, Entity>(Payee, payee));
print('${store.state.entities}');
```

The embedded map is empty:  `{Payee: {}}`

**Comment by davidmorgan** [comment]
Something like this should do it:

`
b.entities[a.payload.p1] = b.entities[a.payload.p1].rebuild((b) => b[a.payload.p2.id] = a.payload.p2);
`

as you had it, it was creating a builder with `toBuilder`, updating it, then discarding it.

It might work better to have a compound key type instead of nesting maps. Depends on what you're doing. So instead of `BuiltMap<Type, BuiltMap<String, Entity>>` you could have `BuiltMap<MyKey, Entity>` where `MyKey` has a field for `Type` another another for `String`.

**Comment by kostaa** [comment]
Thanks for that the update woks now.
Your work is much appreciated!
