### ISSUE TITLE
BuiltMap<String, dynamic> not supported?

### ISSUE THREAD

**Issue by larssn** [google/built_collection.dart#188]
So getting a Map from Firestore is basically always a `Map<String, dynamic>`. I was hoping that BuiltMap also supported mixed maps, as I'd opt to use BuiltMaps instead of Map, internally. But it doesn't look like it?

**Comment by davidmorgan** [comment]
`BuiltMap` (and other built collections) reject `dynamic` purely as a matter of convenience. In Dart 1 it was very easy to accidentally end up with `dynamic` when you really wanted a typed collection. In Dart 2 type inference helps here, but it's still possible to end up with `dynamic` when that's not what you wanted:

```
void main() {
  Map foo = {1: 'one'};
  print(foo.runtimeType.toString());
}
```

The analyzer has 'strict raw types' mode to avoid this. Once that is widely used (part of `package:pedantic`), it will make sense to remove the check for `dynamic` in built collections, since you'll only get it if you ask for it explicitly.

**Comment by larssn** [comment]
So I'm hearing "eventually" :-)

Thanks, we can live with a bit of discipline and just use `Map.from` for now.

**Comment by davidmorgan** [comment]
Right. Maybe sometime this year :)

**Comment by elliottmb** [comment]
@davidmorgan Now that it's 2020, would enabling `dynamic` be doable.

It would make passing around generic json-like payloads easier to have `BuiltMap<String, dynamic>` as an available type instead of having to in this one edge case use `Map.immutable` and hope everyone realizes it is immutable.

**Comment by davidmorgan** [comment]
We're slowly headed towards having 'strict raw types' be part of `package:pedantic`, but not there yet.

**Comment by davidmorgan** [comment]
Allowing `dynamic` is out for review / will be in next release.
