### ISSUE TITLE
Why is there no `toBuiltMap()` extension?

### ISSUE THREAD

**Issue by UnHumbleBen** [google/built_collection.dart#206]
Why isn't there an analogous extension to [toBuildSet](https://pub.dev/documentation/built_collection/latest/built_collection/BuiltSetIterableExtension.html) and [toBuiltList](https://pub.dev/documentation/built_collection/latest/built_collection/BuiltListIterableExtension.html) for `BuiltMap`?

**Comment by davidmorgan** [comment]
`toBuiltSet` and `toBuiltMap` are on `Iterable`. What kind of `Iterable` would you want to convert to a `BuiltMap`? We could do `Iterable<MapEntry<K, V>>`, but I'm not sure those actually turn up a lot, which is why I didn't add it at the same time.

There is already `Map.build()`, e.g. you can do `{1: 'one', 2: 'two'}.build()` to get a `BuiltMap<int, String>`.

**Comment by UnHumbleBen** [comment]
Ah I see thanks for clarification. I was just planning to use it on a `Map`, so like you said, I used `Map.build()`.
