### ISSUE TITLE
BuiltList first & elementAt should be nullable

### ISSUE THREAD

**Issue by smkhalsa** [google/built_collection.dart#233]
Since switching to nnbd, I've had a number of runtime exceptions due to the fact that the return types for `BuiltList.first` and `BuiltList.elementAt` are non-nullable. Pre-nnbd, I was checking for null and handling it appropriately. Now it's throwing.

Was this intentional?

Of course, I could wrap my code in a try / catch and handle any null exceptions thrown. Or I could simply forego `first` and `elementAt` altogether and simply use [] property access. 

However, the existing implementation seems unintuitive and creates an opportunity for silent failures.

If the user knows that `first` or `elementAt` will contain a value, they can always use the `!` operator.

**Comment by davidmorgan** [comment]
Yes, this is intentional, we follow the SDK APIs

https://api.dart.dev/stable/2.10.5/dart-core/List/first.html
https://api.dart.dev/stable/2.10.5/dart-core/Iterable/elementAt.html

note that `BuiltList` should not contain null, but there is a bug right now which means it's possible to put nulls in (I think using 'replace', I don't quite remember). I expect to fix that, and at the same time allow BuiltList<T?> for cases where you do want nulls.

**Comment by smkhalsa** [comment]
> we follow the SDK APIs

Ah, I see. It seems like an odd choice by the Dart lang devs. Thanks for clarifying though. I guess I'll just use `[0]` instead of `first` from now on.

**Comment by smkhalsa** [comment]
> I expect to fix that, and at the same time allow BuiltList<T?> for cases where you do want nulls.

I'm really looking forward to this.
